FROM ubuntu:22.04

RUN apt update && apt install -y \
    build-essential \
    cmake \
    git \
    wget \
    curl \
    python3 \
    python3-pip \
    libssl-dev \
    libz-dev \
    libglib2.0-dev \
    netcat-traditional \
    && rm -rf /var/lib/apt/lists/*
